name: OpenTabletDriver Publish

on:
  workflow_call:
    inputs:
      version_suffix:
        description: 'Optional version suffix (e.g. for release candidates)'
        required: false
        type: string

jobs:
  matrixpublish:
    continue-on-error: true
    env:
      VERSION_SUFFIX: ${{ github.event.inputs.version_suffix }}
    strategy:
      matrix:
        build: [windows, macos, BinaryTarBall, RedHat, Debian, Simple]
        runtime-suffix: [x64, arm64]
        include:
          - build: BinaryTarBall
            os: ubuntu-latest
            runtime-prefix: linux-
          - build: RedHat
            os: ubuntu-latest
            runtime-prefix: linux-
            container: fedora
          - build: Debian
            os: ubuntu-latest
            runtime-prefix: linux-
          - build: Simple
            os: ubuntu-latest
            runtime-prefix: linux-
          - build: macos
            os: macos-15
            runtime-prefix: osx-
            pre-command: brew install coreutils bash; echo "$(brew --prefix coreutils)/libexec/gnubin" >> $GITHUB_PATH
          - build: windows
            os: windows-latest
            runtime-prefix: win-
        exclude:
          - build: RedHat
            runtime-suffix: arm64
          - build: Debian
            runtime-suffix: arm64
    # TODO: release or debug build
    name: ${{ matrix.build }} ${{ matrix.runtime-prefix }}${{ matrix.runtime-suffix }} Publish
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Pre-requisites
        if: ${{ matrix.pre-command }}
        run: |
          echo "Running pre-command setup..."
          eval "${{ matrix.pre-command }}"
      - uses: ./.github/actions/build-wrapper
        with:
          runtime: ${{ matrix.runtime-prefix }}${{ matrix.runtime-suffix }}
          package-name: ${{ matrix.build }}
          container: ${{ matrix.container }}
